import json
import csv
import argparse

parser = argparse.ArgumentParser(description='Parses JSON files generated by wigle_query.py and generates a CSV file')
parser.add_argument('--in', '-i', required=True, type=str, help='JSON file to read.')
parser.add_argument('--out', '-o', required=True, type=str, help='CSV file to write.')
args = vars(parser.parse_args())

data = open(args["in"]).read()
data = json.loads(data.decode('unicode_escape').encode('ascii','ignore'))
outfile = open(args["out"],'w')
csvwriter = csv.writer(outfile)

count = 0
for net in data:
    if count == 0:
            header = net.keys()
            csvwriter.writerow(header)
            count += 1
    csvwriter.writerow(net.values())
outfile.close()
